[package]
name = "hangman-word-rater"
version = "0.1.0"
authors = ["KrisAesoey <kris.aesoey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex= "0.4.0"